Added python checks

diff --git a/utils/setup b/utils/setup
--- a/utils/setup
+++ b/utils/setup
@@ -4,6 +4,15 @@ set -eu
 
 SCRIPT_DIR=${0:a:h}
 
+command -v pipenv >/dev/null 2>&1 || { echo >&2 "Could not find 'pipenv'. Please see the README in the 'qemu' directory on how to install python and pipenv (search for pyenv)."; exit 1; }
+
+if python --version 2>&1 | grep -q '^Python 3\.10\.'; then
+else
+    echo >&2 "Could not find Python in version 3.10. Please see the README in the 'qemu' directory on how to install python (search for pyenv)."
+    exit 1
+fi
+
+exit 1
 cd ${SCRIPT_DIR}/kpatch
 ./setup
 
